"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import google.protobuf.descriptor
import google.protobuf.message
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

@typing.final
class GetNextCandidateRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VIEWER_ID_FIELD_NUMBER: builtins.int
    viewer_id: builtins.int
    def __init__(
        self,
        *,
        viewer_id: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["viewer_id", b"viewer_id"]) -> None: ...

Global___GetNextCandidateRequest: typing_extensions.TypeAlias = GetNextCandidateRequest

@typing.final
class GetNextCandidateResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PROFILE_ID_FIELD_NUMBER: builtins.int
    QUEUE_LEN_FIELD_NUMBER: builtins.int
    profile_id: builtins.int
    queue_len: builtins.int
    def __init__(
        self,
        *,
        profile_id: builtins.int = ...,
        queue_len: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["profile_id", b"profile_id", "queue_len", b"queue_len"]) -> None: ...

Global___GetNextCandidateResponse: typing_extensions.TypeAlias = GetNextCandidateResponse

@typing.final
class UpdateEngagementRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    USER1_TELEGRAM_ID_FIELD_NUMBER: builtins.int
    USER2_TELEGRAM_ID_FIELD_NUMBER: builtins.int
    EVENT_TYPE_FIELD_NUMBER: builtins.int
    user1_telegram_id: builtins.int
    user2_telegram_id: builtins.int
    event_type: builtins.str
    def __init__(
        self,
        *,
        user1_telegram_id: builtins.int = ...,
        user2_telegram_id: builtins.int = ...,
        event_type: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["event_type", b"event_type", "user1_telegram_id", b"user1_telegram_id", "user2_telegram_id", b"user2_telegram_id"]) -> None: ...

Global___UpdateEngagementRequest: typing_extensions.TypeAlias = UpdateEngagementRequest

@typing.final
class UpdateEngagementResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    SUCCESS_FIELD_NUMBER: builtins.int
    success: builtins.bool
    def __init__(
        self,
        *,
        success: builtins.bool = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["success", b"success"]) -> None: ...

Global___UpdateEngagementResponse: typing_extensions.TypeAlias = UpdateEngagementResponse
