# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: api/ranking_api/v1/ranking.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    34,
    1,
    '',
    'api/ranking_api/v1/ranking.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n api/ranking_api/v1/ranking.proto\x12\x0eranking_api.v1\",\n\x17GetNextCandidateRequest\x12\x11\n\tviewer_id\x18\x01 \x01(\x03\"A\n\x18GetNextCandidateResponse\x12\x12\n\nprofile_id\x18\x01 \x01(\x03\x12\x11\n\tqueue_len\x18\x02 \x01(\x03\x32w\n\x0eRankingService\x12\x65\n\x10GetNextCandidate\x12\'.ranking_api.v1.GetNextCandidateRequest\x1a(.ranking_api.v1.GetNextCandidateResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'api.ranking_api.v1.ranking_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETNEXTCANDIDATEREQUEST']._serialized_start=52
  _globals['_GETNEXTCANDIDATEREQUEST']._serialized_end=96
  _globals['_GETNEXTCANDIDATERESPONSE']._serialized_start=98
  _globals['_GETNEXTCANDIDATERESPONSE']._serialized_end=163
  _globals['_RANKINGSERVICE']._serialized_start=165
  _globals['_RANKINGSERVICE']._serialized_end=284
# @@protoc_insertion_point(module_scope)
