syntax = "proto3";
package ranking_api.v1;

service RankingService {
  rpc GetNextCandidate(GetNextCandidateRequest) returns (GetNextCandidateResponse);
  rpc UpdateEngagement(UpdateEngagementRequest) returns (UpdateEngagementResponse);
}

message GetNextCandidateRequest {
  int64 viewer_id = 1;
}

message GetNextCandidateResponse {
  int64 profile_id = 1;
  int64 queue_len = 2;
}

message UpdateEngagementRequest {
  int64 user1_telegram_id = 1;
  int64 user2_telegram_id = 2;
  string event_type = 3;
}

message UpdateEngagementResponse {
  bool success = 1;
}