# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: ranking_api/v1/ranking.proto
# Protobuf Python Version: 7.34.1
"""Generated protocol buffer code."""

from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder

_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC, 7, 34, 1, "", "ranking_api/v1/ranking.proto"
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(
    b'\n\x1cranking_api/v1/ranking.proto\x12\x0eranking_api.v1",\n\x17GetNextCandidateRequest\x12\x11\n\tviewer_id\x18\x01 \x01(\x03"A\n\x18GetNextCandidateResponse\x12\x12\n\nprofile_id\x18\x01 \x01(\x03\x12\x11\n\tqueue_len\x18\x02 \x01(\x03"c\n\x17UpdateEngagementRequest\x12\x19\n\x11user1_telegram_id\x18\x01 \x01(\x03\x12\x19\n\x11user2_telegram_id\x18\x02 \x01(\x03\x12\x12\n\nevent_type\x18\x03 \x01(\t"+\n\x18UpdateEngagementResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x32\xde\x01\n\x0eRankingService\x12\x65\n\x10GetNextCandidate\x12\'.ranking_api.v1.GetNextCandidateRequest\x1a(.ranking_api.v1.GetNextCandidateResponse\x12\x65\n\x10UpdateEngagement\x12\'.ranking_api.v1.UpdateEngagementRequest\x1a(.ranking_api.v1.UpdateEngagementResponseb\x06proto3'
)

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, "ranking_api.v1.ranking_pb2", _globals)
if not _descriptor._USE_C_DESCRIPTORS:
    DESCRIPTOR._loaded_options = None
    _globals["_GETNEXTCANDIDATEREQUEST"]._serialized_start = 48
    _globals["_GETNEXTCANDIDATEREQUEST"]._serialized_end = 92
    _globals["_GETNEXTCANDIDATERESPONSE"]._serialized_start = 94
    _globals["_GETNEXTCANDIDATERESPONSE"]._serialized_end = 159
    _globals["_UPDATEENGAGEMENTREQUEST"]._serialized_start = 161
    _globals["_UPDATEENGAGEMENTREQUEST"]._serialized_end = 260
    _globals["_UPDATEENGAGEMENTRESPONSE"]._serialized_start = 262
    _globals["_UPDATEENGAGEMENTRESPONSE"]._serialized_end = 305
    _globals["_RANKINGSERVICE"]._serialized_start = 308
    _globals["_RANKINGSERVICE"]._serialized_end = 530
# @@protoc_insertion_point(module_scope)
