# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: api/ranking_api/v1/ranking.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import api.ranking_api.v1.ranking_pb2


class RankingServiceBase(abc.ABC):

    @abc.abstractmethod
    async def GetNextCandidate(self, stream: 'grpclib.server.Stream[api.ranking_api.v1.ranking_pb2.GetNextCandidateRequest, api.ranking_api.v1.ranking_pb2.GetNextCandidateResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/ranking_api.v1.RankingService/GetNextCandidate': grpclib.const.Handler(
                self.GetNextCandidate,
                grpclib.const.Cardinality.UNARY_UNARY,
                api.ranking_api.v1.ranking_pb2.GetNextCandidateRequest,
                api.ranking_api.v1.ranking_pb2.GetNextCandidateResponse,
            ),
        }


class RankingServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.GetNextCandidate = grpclib.client.UnaryUnaryMethod(
            channel,
            '/ranking_api.v1.RankingService/GetNextCandidate',
            api.ranking_api.v1.ranking_pb2.GetNextCandidateRequest,
            api.ranking_api.v1.ranking_pb2.GetNextCandidateResponse,
        )
