# Generated by the Protocol Buffers compiler. DO NOT EDIT!
# source: profile_api/v1/profile.proto
# plugin: grpclib.plugin.main
import abc
import typing

import grpclib.const
import grpclib.client
if typing.TYPE_CHECKING:
    import grpclib.server

import external_clients.profile_api.v1.profile_pb2 as profile_pb2


class ProfileServiceBase(abc.ABC):

    @abc.abstractmethod
    async def Health(self, stream: 'grpclib.server.Stream[profile_pb2.HealthRequest, profile_pb2.HealthResponse]') -> None:
        pass

    @abc.abstractmethod
    async def CreateProfile(self, stream: 'grpclib.server.Stream[profile_pb2.CreateProfileRequest, profile_pb2.CreateProfileResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetProfile(self, stream: 'grpclib.server.Stream[profile_pb2.GetProfileRequest, profile_pb2.GetProfileResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetProfileById(self, stream: 'grpclib.server.Stream[profile_pb2.GetProfileByIdRequest, profile_pb2.GetProfileByIdResponse]') -> None:
        pass

    @abc.abstractmethod
    async def UpdateProfile(self, stream: 'grpclib.server.Stream[profile_pb2.UpdateProfileRequest, profile_pb2.UpdateProfileResponse]') -> None:
        pass

    @abc.abstractmethod
    async def SetGeo(self, stream: 'grpclib.server.Stream[profile_pb2.SetGeoRequest, profile_pb2.SetGeoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def UploadPhoto(self, stream: 'grpclib.server.Stream[profile_pb2.UploadPhotoRequest, profile_pb2.UploadPhotoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def DeletePhoto(self, stream: 'grpclib.server.Stream[profile_pb2.DeletePhotoRequest, profile_pb2.DeletePhotoResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetPresignedUrl(self, stream: 'grpclib.server.Stream[profile_pb2.GetPresignedUrlRequest, profile_pb2.GetPresignedUrlResponse]') -> None:
        pass

    @abc.abstractmethod
    async def SetPreferences(self, stream: 'grpclib.server.Stream[profile_pb2.SetPreferencesRequest, profile_pb2.SetPreferencesResponse]') -> None:
        pass

    @abc.abstractmethod
    async def GetPreferences(self, stream: 'grpclib.server.Stream[profile_pb2.GetPreferencesRequest, profile_pb2.GetPreferencesResponse]') -> None:
        pass

    def __mapping__(self) -> typing.Dict[str, grpclib.const.Handler]:
        return {
            '/profile_api.v1.ProfileService/Health': grpclib.const.Handler(
                self.Health,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.HealthRequest,
                profile_pb2.HealthResponse,
            ),
            '/profile_api.v1.ProfileService/CreateProfile': grpclib.const.Handler(
                self.CreateProfile,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.CreateProfileRequest,
                profile_pb2.CreateProfileResponse,
            ),
            '/profile_api.v1.ProfileService/GetProfile': grpclib.const.Handler(
                self.GetProfile,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.GetProfileRequest,
                profile_pb2.GetProfileResponse,
            ),
            '/profile_api.v1.ProfileService/GetProfileById': grpclib.const.Handler(
                self.GetProfileById,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.GetProfileByIdRequest,
                profile_pb2.GetProfileByIdResponse,
            ),
            '/profile_api.v1.ProfileService/UpdateProfile': grpclib.const.Handler(
                self.UpdateProfile,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.UpdateProfileRequest,
                profile_pb2.UpdateProfileResponse,
            ),
            '/profile_api.v1.ProfileService/SetGeo': grpclib.const.Handler(
                self.SetGeo,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.SetGeoRequest,
                profile_pb2.SetGeoResponse,
            ),
            '/profile_api.v1.ProfileService/UploadPhoto': grpclib.const.Handler(
                self.UploadPhoto,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.UploadPhotoRequest,
                profile_pb2.UploadPhotoResponse,
            ),
            '/profile_api.v1.ProfileService/DeletePhoto': grpclib.const.Handler(
                self.DeletePhoto,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.DeletePhotoRequest,
                profile_pb2.DeletePhotoResponse,
            ),
            '/profile_api.v1.ProfileService/GetPresignedUrl': grpclib.const.Handler(
                self.GetPresignedUrl,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.GetPresignedUrlRequest,
                profile_pb2.GetPresignedUrlResponse,
            ),
            '/profile_api.v1.ProfileService/SetPreferences': grpclib.const.Handler(
                self.SetPreferences,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.SetPreferencesRequest,
                profile_pb2.SetPreferencesResponse,
            ),
            '/profile_api.v1.ProfileService/GetPreferences': grpclib.const.Handler(
                self.GetPreferences,
                grpclib.const.Cardinality.UNARY_UNARY,
                profile_pb2.GetPreferencesRequest,
                profile_pb2.GetPreferencesResponse,
            ),
        }


class ProfileServiceStub:

    def __init__(self, channel: grpclib.client.Channel) -> None:
        self.Health = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/Health',
            profile_pb2.HealthRequest,
            profile_pb2.HealthResponse,
        )
        self.CreateProfile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/CreateProfile',
            profile_pb2.CreateProfileRequest,
            profile_pb2.CreateProfileResponse,
        )
        self.GetProfile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/GetProfile',
            profile_pb2.GetProfileRequest,
            profile_pb2.GetProfileResponse,
        )
        self.GetProfileById = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/GetProfileById',
            profile_pb2.GetProfileByIdRequest,
            profile_pb2.GetProfileByIdResponse,
        )
        self.UpdateProfile = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/UpdateProfile',
            profile_pb2.UpdateProfileRequest,
            profile_pb2.UpdateProfileResponse,
        )
        self.SetGeo = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/SetGeo',
            profile_pb2.SetGeoRequest,
            profile_pb2.SetGeoResponse,
        )
        self.UploadPhoto = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/UploadPhoto',
            profile_pb2.UploadPhotoRequest,
            profile_pb2.UploadPhotoResponse,
        )
        self.DeletePhoto = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/DeletePhoto',
            profile_pb2.DeletePhotoRequest,
            profile_pb2.DeletePhotoResponse,
        )
        self.GetPresignedUrl = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/GetPresignedUrl',
            profile_pb2.GetPresignedUrlRequest,
            profile_pb2.GetPresignedUrlResponse,
        )
        self.SetPreferences = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/SetPreferences',
            profile_pb2.SetPreferencesRequest,
            profile_pb2.SetPreferencesResponse,
        )
        self.GetPreferences = grpclib.client.UnaryUnaryMethod(
            channel,
            '/profile_api.v1.ProfileService/GetPreferences',
            profile_pb2.GetPreferencesRequest,
            profile_pb2.GetPreferencesResponse,
        )
